### PR TITLE
Add adapter to handle arbitrary socket options

### PR DESCRIPTION
**Pull request by sigmavirus24**
Also add an adapter that gives users a simple way to configure TCP
Keep-Alive.

TODO:

- [x] tests
- [ ] add docs

### CODE REVIEW

**Comment by Lukasa** [comment]
Sems reasonable to me.

**Comment by sigmavirus24** [comment]
@Lukasa to give this one more look?

**Comment by Lukasa** [comment]
LGTM. :cake:

**Comment by sigmavirus24** [comment]
Just adding some quick documentation, after which I'll push, verify everything passes, and merge. Thanks @Lukasa :cake:

**Pull request merged**
